language: node_js
node_js:
- node
os:
- linux
notifications:
  email: false
script:
- npm run ci
deploy:
  provider: heroku
  api_key:
    secure: ANBWpxJ2Jct8fXncE1J/37adKuNsFmzopNzgbhqcK4fehaHjd/icJfybnH4gz2L+l9clFZrrSAe3zVvSREM79m/QHW2YeeTEtUktjHd0XZpgA9FrxuDJCm+6SMcCiwr38H0E6McyBgp/Yu5N+g6M2lym56MW8J0+8hb9yI4Oso1DQ7JHzQZrpHFY8H/3lfgy8LwICJT/f2ypV9iv8MlQJxKkITp1c1J97jA9MLtu6Yds1nzBQ1sAleDzoz3utOXnZ4mMn6jMbGKCg2EY8W7T3J2ZSAUpz9U4o2zUpFxxbMr7WUdBI0v7wizzKcA2TYeUMovARBFJtteDA/ya+zQ3hzVPjQO3YpbA2OywZ8Zshyt3Fwm4EA9Wq2nS8j/Edcr2eCOUpVlX1ShREvW0Xdbdsla7PrKmsXvMJ64PLnpy+Y7XLLcyum3gGzZO9oWdwo+gI9NlWFsd5io6zQ+Wuc950diniJoNTeYHtXiREDq9Ev0ZZcoaUo0ojMavaCmYHMV0iasXqSr3YSvRPT+RtCWwgkDg0PgNOjKQo9gvQXjcBbTqXixCX7VszsqnWpeSvMfA7omeE1+ZyGAX308KzfXHuYXhjLzX0AIEUqyIrS47bkAb0CiV96zeEl2CLtnq1rrUHt5fAJCKl9aT6MwusM6krwsje1jrksSv+K/+zhvPFds=
  app:
    master: shri-hw-node-git
  on:
    repo: drinkins85/shri-hw-node-git
